version: '3'

services:
  web:
    build: .
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    networks:
      - demo_network
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=8080

networks:
  demo_network:
    driver: bridge