version: '3'

services:
  redis:
    image: redis:latest
    restart: always
    networks:
      - demo_network
    ports:
      - "6379:6379"
    expose:
      - "6379"
    
networks:
  demo_network:
    driver: bridge